version: "3.8"
services:
  web:
    build: .
    volumes:
      - ./wms/:/www/
      - ./:/tmp/
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: warehouse